using NUnit.Framework;
using UKRobotics.D2.DispenseLib.Calibration;

namespace UKRobotics.D2.DispenseLibTest.Calibration
{
    public static class CalibrationTestUtils
    {



        public static void AssertPoint(double openTimeUSecs, int shotCount, double massGrams, CalibrationPoint point)
        {
            Assert.AreEqual(openTimeUSecs, point.OpenTimeUSecs);
            Assert.AreEqual(shotCount, point.ShotCount);
            Assert.AreEqual(massGrams, point.Mass.Grams);
        }



        public const string Json1 = @"{
   ""activeCalibrations"":[
      {
         ""_id"":""61bb4ce897bfdcd79eb6b73d"",
         ""deviceSerialId"":""dd042367ca4c57ad9860fe643af3dc6b"",
         ""valveChannelNumber"":1,
         ""calibrationId"":""61ba0aec23f58d497724c48f"",
         ""calibration"":[
            {
               ""_id"":""61ba0aec23f58d497724c48f"",
               ""density"":998.201,
               ""fluidName"":""Water_4Point"",
               ""pressure"":0.5,
               ""valveType"":""19524"",
               ""valveSerialNumber"":"""",
               ""notes"":"""",
               ""points"":[
                  {
                     ""openTimeUSecs"":200,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":4200,
                     ""massGrams"":0.183
                  },
                  {
                     ""openTimeUSecs"":300,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":2600,
                     ""massGrams"":0.1375
                  },
                  {
                     ""openTimeUSecs"":500,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":2000,
                     ""massGrams"":0.1235
                  },
                  {
                     ""openTimeUSecs"":1000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":1600,
                     ""massGrams"":0.1415
                  },
                  {
                     ""openTimeUSecs"":2500,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":750,
                     ""massGrams"":0.124
                  },
                  {
                     ""openTimeUSecs"":4000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":480,
                     ""massGrams"":0.142
                  },
                  {
                     ""openTimeUSecs"":8000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":250,
                     ""massGrams"":0.201
                  },
                  {
                     ""openTimeUSecs"":10000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":200,
                     ""massGrams"":0.2205
                  },
                  {
                     ""openTimeUSecs"":20000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":100,
                     ""massGrams"":0.284
                  },
                  {
                     ""openTimeUSecs"":1000000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":1,
                     ""massGrams"":0.1865
                  }
               ],
               ""modifiedTime"":""2021-12-15T19:01:09.043Z"",
               ""userId"":""d3ca06ac-c9fc-4e68-b7ab-e9dd272cf7c4"",
               ""userEmail"":""mcounsell@ukrobotics.net"",
               ""deviceSerialId"":""dd042367ca4c57ad9860fe643af3dc6b""
            }
         ]
      },
      {
         ""_id"":""61bb4ced97bfdcd79eb6b7c7"",
         ""deviceSerialId"":""dd042367ca4c57ad9860fe643af3dc6b"",
         ""valveChannelNumber"":2,
         ""calibrationId"":""61ba0aec23f58d497724c48f"",
         ""calibration"":[
            {
               ""_id"":""61ba0aec23f58d497724c48f"",
               ""density"":998.201,
               ""fluidName"":""Water_4Point"",
               ""pressure"":0.5,
               ""valveType"":""19524"",
               ""valveSerialNumber"":"""",
               ""notes"":"""",
               ""points"":[
                  {
                     ""openTimeUSecs"":200,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":4200,
                     ""massGrams"":0.183
                  },
                  {
                     ""openTimeUSecs"":300,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":2600,
                     ""massGrams"":0.1375
                  },
                  {
                     ""openTimeUSecs"":500,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":2000,
                     ""massGrams"":0.1235
                  },
                  {
                     ""openTimeUSecs"":1000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":1600,
                     ""massGrams"":0.1415
                  },
                  {
                     ""openTimeUSecs"":2500,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":750,
                     ""massGrams"":0.124
                  },
                  {
                     ""openTimeUSecs"":4000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":480,
                     ""massGrams"":0.142
                  },
                  {
                     ""openTimeUSecs"":8000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":250,
                     ""massGrams"":0.201
                  },
                  {
                     ""openTimeUSecs"":10000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":200,
                     ""massGrams"":0.2205
                  },
                  {
                     ""openTimeUSecs"":20000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":100,
                     ""massGrams"":0.284
                  },
                  {
                     ""openTimeUSecs"":1000000,
                     ""interShotTimeUSecs"":100000,
                     ""shotCount"":1,
                     ""massGrams"":0.1865
                  }
               ],
               ""modifiedTime"":""2021-12-15T19:01:09.043Z"",
               ""userId"":""d3ca06ac-c9fc-4e68-b7ab-e9dd272cf7c4"",
               ""userEmail"":""mcounsell@ukrobotics.net"",
               ""deviceSerialId"":""dd042367ca4c57ad9860fe643af3dc6b""
            }
         ]
      }
   ]
}";
    }
}